" Name:         queque
" Description:  A take on a colorscheme.
" Author:       Rafael Albuquerque <me@rafael.pt>
" Maintainer:   Rafael Albuquerque <me@rafael.pt>
" Website:      https://rafael.pt
" License:      Public domain
" Last Updated: Mon 28 Mar 12:27:01 2022

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'queque'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#f07575', '#6ad899', '#fff965', '#99bdff', '#f7889d', '#1fe6d1', '#ebebeb', '#999999', '#ffa15c', '#b5f88b', '#ffff64', '#56a9e1', '#ff8ffa', '#33ffc2', '#e0e0ed']
  if get(g:, 'queque_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
    hi Terminal guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#000000 gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi CursorColumn guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi CursorLine guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi DiffAdd guifg=#ebebeb guibg=#000000 gui=reverse cterm=reverse
  hi DiffChange guifg=#ebebeb guibg=#000000 gui=reverse cterm=reverse
  hi DiffDelete guifg=#ebebeb guibg=#000000 gui=reverse cterm=reverse
  hi DiffText guifg=#ebebeb guibg=#000000 gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ebebeb guibg=#000000 gui=reverse cterm=reverse
  hi FoldColumn guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi Folded guifg=#ebebeb guibg=#000000 gui=italic cterm=italic
  hi IncSearch guifg=#000000 guibg=#fff965 gui=NONE cterm=NONE
  hi LineNr guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi MatchParen guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi ModeMsg guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi MoreMsg guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi NonText guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi Pmenu guifg=#ebebeb guibg=#333333 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#ebebeb guibg=#333333 gui=NONE cterm=NONE
  hi PmenuSel guifg=#ebebeb guibg=#333333 gui=reverse cterm=reverse
  hi PmenuThumb guifg=#ebebeb guibg=#333333 gui=NONE cterm=NONE
  hi Question guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi Search guifg=#000000 guibg=#fff965 gui=NONE cterm=NONE
  hi SignColumn guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi SpecialKey guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi SpellBad guifg=#ebebeb guibg=#000000 guisp=#f07575 gui=NONE cterm=NONE
  hi SpellCap guifg=#ebebeb guibg=#000000 guisp=#99bdff gui=NONE cterm=NONE
  hi SpellLocal guifg=#ebebeb guibg=#000000 guisp=#f7889d gui=NONE cterm=NONE
  hi SpellRare guifg=#ebebeb guibg=#000000 guisp=#1fe6d1 gui=reverse cterm=reverse
  hi StatusLine guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi TabLine guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi TabLineFill guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi TabLineSel guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi Title guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi VertSplit guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi Visual guifg=#ebebeb guibg=#999999 gui=NONE cterm=NONE
  hi VisualNOS guifg=#ebebeb guibg=#999999 gui=NONE cterm=NONE
  hi WarningMsg guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi WildMenu guifg=#ebebeb guibg=#000000 gui=NONE cterm=NONE
  hi Comment guifg=#999999 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#b5f88b guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#f07575 guibg=#000000 gui=reverse cterm=reverse
  hi Identifier guifg=#1fe6d1 guibg=NONE gui=bold cterm=bold
  hi Ignore guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#fff965 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#99bdff guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#999999 guibg=NONE gui=bold,underline cterm=bold,underline
  hi Type guifg=#6ad899 guibg=NONE gui=bold cterm=bold
  hi Underlined guifg=#ebebeb guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#000000 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ebebeb guibg=#000000 gui=bold cterm=bold
  hi pythonOperator guifg=#ffa15c guibg=NONE gui=NONE cterm=NONE
  hi pythonConditional guifg=#ffa15c guibg=NONE gui=bold cterm=bold
  hi pythonRepeat guifg=#ffa15c guibg=NONE gui=bold cterm=bold
  hi pythonBuiltinObj guifg=#ff8ffa guibg=NONE gui=bold cterm=bold
  hi pythonBuiltinType guifg=#ff8ffa guibg=NONE gui=bold cterm=bold
  hi pythonException guifg=#f07575 guibg=NONE gui=bold cterm=bold
  hi pythonSelf guifg=#6ad899 guibg=NONE gui=bold cterm=bold
  hi pythonFunctionCall guifg=#33ffc2 guibg=NONE gui=NONE cterm=NONE
  hi pythonDottedName guifg=#ffa15c guibg=NONE gui=bold,underline cterm=bold,underline
  hi pythonInclude guifg=#fff965 guibg=NONE gui=bold cterm=bold
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'queque_transp_bg', 0)
    hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=255 ctermbg=16 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=255 ctermbg=16 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=16 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=255 ctermbg=16 cterm=NONE
  hi CursorColumn ctermfg=255 ctermbg=16 cterm=NONE
  hi CursorLine ctermfg=255 ctermbg=16 cterm=NONE
  hi CursorLineNr ctermfg=255 ctermbg=16 cterm=NONE
  hi DiffAdd ctermfg=255 ctermbg=16 cterm=reverse
  hi DiffChange ctermfg=255 ctermbg=16 cterm=reverse
  hi DiffDelete ctermfg=255 ctermbg=16 cterm=reverse
  hi DiffText ctermfg=255 ctermbg=16 cterm=bold,reverse
  hi Directory ctermfg=255 ctermbg=16 cterm=NONE
  hi EndOfBuffer ctermfg=255 ctermbg=16 cterm=NONE
  hi ErrorMsg ctermfg=255 ctermbg=16 cterm=reverse
  hi FoldColumn ctermfg=255 ctermbg=16 cterm=NONE
  hi Folded ctermfg=255 ctermbg=16 cterm=italic
  hi IncSearch ctermfg=16 ctermbg=227 cterm=NONE
  hi LineNr ctermfg=255 ctermbg=16 cterm=NONE
  hi MatchParen ctermfg=255 ctermbg=16 cterm=NONE
  hi ModeMsg ctermfg=255 ctermbg=16 cterm=NONE
  hi MoreMsg ctermfg=255 ctermbg=16 cterm=NONE
  hi NonText ctermfg=255 ctermbg=16 cterm=NONE
  hi Pmenu ctermfg=255 ctermbg=236 cterm=NONE
  hi PmenuSbar ctermfg=255 ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=255 ctermbg=236 cterm=reverse
  hi PmenuThumb ctermfg=255 ctermbg=236 cterm=NONE
  hi Question ctermfg=255 ctermbg=16 cterm=NONE
  hi Search ctermfg=16 ctermbg=227 cterm=NONE
  hi SignColumn ctermfg=255 ctermbg=16 cterm=NONE
  hi SpecialKey ctermfg=255 ctermbg=16 cterm=NONE
  hi SpellBad ctermfg=255 ctermbg=16 cterm=NONE
  hi SpellCap ctermfg=255 ctermbg=16 cterm=NONE
  hi SpellLocal ctermfg=255 ctermbg=16 cterm=NONE
  hi SpellRare ctermfg=255 ctermbg=16 cterm=reverse
  hi StatusLine ctermfg=255 ctermbg=16 cterm=NONE
  hi StatusLineNC ctermfg=255 ctermbg=16 cterm=NONE
  hi TabLine ctermfg=255 ctermbg=16 cterm=NONE
  hi TabLineFill ctermfg=255 ctermbg=16 cterm=NONE
  hi TabLineSel ctermfg=255 ctermbg=16 cterm=NONE
  hi Title ctermfg=255 ctermbg=16 cterm=NONE
  hi VertSplit ctermfg=255 ctermbg=16 cterm=NONE
  hi Visual ctermfg=255 ctermbg=247 cterm=NONE
  hi VisualNOS ctermfg=255 ctermbg=247 cterm=NONE
  hi WarningMsg ctermfg=255 ctermbg=16 cterm=NONE
  hi WildMenu ctermfg=255 ctermbg=16 cterm=NONE
  hi Comment ctermfg=247 ctermbg=NONE cterm=italic
  hi Constant ctermfg=156 ctermbg=NONE cterm=NONE
  hi Error ctermfg=210 ctermbg=16 cterm=reverse
  hi Identifier ctermfg=43 ctermbg=NONE cterm=bold
  hi Ignore ctermfg=255 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=227 ctermbg=NONE cterm=NONE
  hi Special ctermfg=255 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=111 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=247 ctermbg=NONE cterm=bold,underline
  hi Type ctermfg=78 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=255 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=16 cterm=NONE
  hi ToolbarButton ctermfg=255 ctermbg=16 cterm=bold
  hi pythonOperator ctermfg=215 ctermbg=NONE cterm=NONE
  hi pythonConditional ctermfg=215 ctermbg=NONE cterm=bold
  hi pythonRepeat ctermfg=215 ctermbg=NONE cterm=bold
  hi pythonBuiltinObj ctermfg=213 ctermbg=NONE cterm=bold
  hi pythonBuiltinType ctermfg=213 ctermbg=NONE cterm=bold
  hi pythonException ctermfg=210 ctermbg=NONE cterm=bold
  hi pythonSelf ctermfg=78 ctermbg=NONE cterm=bold
  hi pythonFunctionCall ctermfg=49 ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=215 ctermbg=NONE cterm=bold,underline
  hi pythonInclude ctermfg=227 ctermbg=NONE cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'queque_transp_bg', 0)
    hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi DiffText ctermfg=LightGrey ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi FoldColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Folded ctermfg=LightGrey ctermbg=Black cterm=italic
  hi IncSearch ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi LineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ModeMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi NonText ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PmenuSbar ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=LightGrey ctermbg=NONE cterm=reverse
  hi PmenuThumb ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Question ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Search ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi SignColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellCap ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellLocal ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpellRare ctermfg=LightGrey ctermbg=Black cterm=reverse
  hi StatusLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Title ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Visual ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi VisualNOS ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi WarningMsg ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=Black cterm=reverse
  hi Identifier ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkGrey ctermbg=NONE cterm=bold,underline
  hi Type ctermfg=DarkGreen ctermbg=NONE cterm=bold
  hi Underlined ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=LightGrey ctermbg=Black cterm=bold
  hi pythonOperator ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi pythonConditional ctermfg=LightRed ctermbg=NONE cterm=bold
  hi pythonRepeat ctermfg=LightRed ctermbg=NONE cterm=bold
  hi pythonBuiltinObj ctermfg=LightMagenta ctermbg=NONE cterm=bold
  hi pythonBuiltinType ctermfg=LightMagenta ctermbg=NONE cterm=bold
  hi pythonException ctermfg=DarkRed ctermbg=NONE cterm=bold
  hi pythonSelf ctermfg=DarkGreen ctermbg=NONE cterm=bold
  hi pythonFunctionCall ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=LightRed ctermbg=NONE cterm=bold,underline
  hi pythonInclude ctermfg=DarkYellow ctermbg=NONE cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #000000                   ~         Black
" Color: red           #F07575                   ~         DarkRed
" Color: green         #6AD899                   ~         DarkGreen
" Color: yellow        #fff965                   ~         DarkYellow
" Color: blue          #99BDFF                   ~         DarkBlue
" Color: magenta       #f7889d                   ~         DarkMagenta
" Color: cyan          #1FE6D1                   ~         DarkCyan
" Color: white         rgb(235, 235, 235)        ~         LightGrey
" Color: brightblack   #999999                   ~         DarkGrey
" Color: brightred     #FFA15C                   ~         LightRed
" Color: brightgreen   #B5F88B                   ~         LightGreen
" Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
" Color: brightblue    #56a9e1                   ~         LightBlue
" Color: brightmagenta #ff8ffa                   ~         LightMagenta
" Color: brightcyan    #33ffc2                   ~         LightCyan
" Color: brightwhite   #e0e0ed                  231        White
" Color: popupbg       #333333 ~ none
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
